// The Node entry point: a real WebSocket server wrapped around the host in ./index.js,
// and — on the same port — the static server for the built client.
//
// Everything platform-specific lives here and nowhere else — the `ws` library, the hrtime
// clock, and the ranks.json store on disk. The host itself knows about none of them, which
// is what lets client/src/localserver.js run the same host in a browser with no server at
// all. See the header of ./index.js for the shape of that seam.
//
//   npm run server      this file
//   npm run dev         this file plus vite (vite serves the page, this serves the game)
//   npm run dev:lan     the same, with vite reachable from other devices on the network
//   npm start           this file alone, serving dist/ as well — what a deploy runs
//
// ONE PORT, TWO PROTOCOLS, and that is the whole reason the http server is here. A WebSocket
// starts life as an HTTP request carrying `Upgrade: websocket`, so a single listener can hand
// those to `ws` and answer everything else with a file. Three things fall out of it that are
// each worth more than the twenty lines it costs:
//
//   one deploy      A host that runs this process serves the client and the game together.
//                   There is no second service to stand up, no CORS, and no URL to paste.
//   no mixed content  A page served over https gets a wss socket back from the same origin.
//                   A browser refuses ws:// from an https: page outright, so a client on one
//                   host and a game server on another is the arrangement that needs work,
//                   not this one.
//   one env var     Cloud hosts hand a process the port to listen on in PORT and route 443
//                   to it. Reading it is the difference between deployable and not.
//
// The client still has to be told to dial back here rather than run its own in-page host, and
// that is a build-time value: `VITE_SERVER=origin npm run build`. See the host block at the
// top of client/src/main.js for the three ways that decision can be made.

import { createServer } from 'node:http';
import { randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { extname, join, normalize, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { WebSocketServer } from 'ws';
import * as C from '../shared/constants.js';
import { MSG, decode, encode } from '../shared/protocol.js';
import { REGIONS, regionsFromEnv } from '../shared/regions.js';
import { createHost } from './index.js';
// The only filesystem-touching module under server/, and imported here and nowhere
// else — see the header of ranks.js for why room.js must not reach it.
import * as ranks from './ranks.js';

/** A cloud host names the port; a checkout does not, and gets the one the client's dev
 *  default already dials. */
const PORT = Number(process.env.PORT) || C.NET_PORT;

/** Where `vite build` puts the client. Absolute, because a deploy's working directory is
 *  nobody's promise. */
const WEB_ROOT = resolve(fileURLToPath(new URL('.', import.meta.url)), '..', 'dist');

/**
 * Which region THIS process is, and the addresses of the others — both from the environment,
 * because neither is a fact about the source code.
 *
 * A region's hostname is generated by whoever hosts it and differs per account, so it cannot
 * be compiled into a bundle without making "add a region" mean "rebuild and redeploy every
 * other region". Read here, served over /regions, and the client uses whatever it is told.
 *
 *   FPSBONE_REGION=sea
 *   FPSBONE_REGIONS=sea=https://fpsbone-sea.onrender.com,usw=https://fpsbone-us.onrender.com
 *   FPSBONE_PEER_USW=fpsbone-usw.onrender.com     one peer per var, for a blueprint that
 *                                                 cannot build the string above
 *
 * Unset is the honest default for a checkout: one server, no region, and the menu offers the
 * only host there is. An unknown id is refused rather than passed through — see the comment
 * on `parseRegions` for why a region nobody can label is worse than a region that is missing.
 *
 * All of it is read in `regionsFromEnv`, next to the parser it feeds, so `verify` can test the
 * whole path with a plain object instead of standing this process up with a doctored env.
 */
const { region: REGION, regions: PEERS, dropped: BAD_PEERS } = regionsFromEnv(process.env);

/**
 * Answered by /ping and /regions, and `*` on purpose.
 *
 * The menu on a page served by ONE region has to ask EVERY region how far away it is, and
 * those are cross-origin requests: without this header the browser hands the page an opaque
 * failure and every region but its own reads as unreachable. What it exposes is a lobby count
 * and a clock reading, which is the same thing anybody learns by opening the game.
 *
 * Kept to plain GETs with no custom headers, so these stay "simple requests" and no
 * preflight is needed — an OPTIONS round trip would double the measured ping.
 */
const CORS = { 'access-control-allow-origin': '*' };

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.mjs': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.webp': 'image/webp',
  '.ico': 'image/x-icon',
  '.woff2': 'font/woff2',
  '.mp3': 'audio/mpeg',
  '.wav': 'audio/wav',
  '.map': 'application/json; charset=utf-8',
};

const host = createHost({
  nowNs: process.hrtime.bigint,
  ranks,
  region: REGION,
  log: (line) => console.log(line),
});

/**
 * Resolve a request path to a file inside WEB_ROOT, or null.
 *
 * The `startsWith` check is the point of the function and not a formality: without it
 * `GET /../../ranks.json` is a request this process would happily answer. `normalize`
 * collapses the traversal first, and anything that still lands outside the root is refused
 * rather than clamped, because a path that tried is not a path to guess the intent of.
 */
function resolveFile(urlPath) {
  const clean = decodeURIComponent(urlPath.split('?')[0].split('#')[0]);
  const rel = normalize(clean === '/' ? 'index.html' : clean.replace(/^\/+/, ''));
  const abs = join(WEB_ROOT, rel);
  if (abs !== WEB_ROOT && !abs.startsWith(WEB_ROOT + sep)) return null;
  return abs;
}

async function serveStatic(req, res) {
  // A health path, because most hosts want one and every one of them wants it to be cheap.
  // It answers before the filesystem is touched, so it stays up even with no dist/ built.
  if (req.url === '/healthz') {
    res.writeHead(200, { 'content-type': 'text/plain; charset=utf-8' });
    res.end(`ok ${host.available.join(',')}`);
    return;
  }

  /**
   * The smallest possible answer, and the thing the menu times.
   *
   * A region's ping is measured by fetching this and watching the clock, so everything about
   * it is in service of not lying about that number:
   *
   *   no-store   a cached response reports a 0ms ocean. This is the whole reason the header
   *              is here, and leaving it off produces a bug that looks like a triumph.
   *   tiny       one small JSON object, so what is measured is the round trip and not the
   *              time to push bytes down a slow uplink.
   *   before I/O no disk, no room walk beyond a count that is already in memory — a server
   *              busy simulating four full lobbies must not report itself as far away.
   *
   * The occupancy rides along because the client is making the request anyway, and "ASIA
   * 41ms · 6 playing" is the pair of facts a player actually chooses on. An empty region with
   * a great ping is not the better room.
   */
  if (req.url === '/ping') {
    const lob = host.occupancy();
    let humans = 0;
    for (const n of Object.values(lob)) humans += n;
    res.writeHead(200, {
      ...CORS,
      'content-type': 'application/json; charset=utf-8',
      'cache-control': 'no-store',
    });
    res.end(JSON.stringify({ r: REGION, lob, humans, t: Date.now() }));
    return;
  }

  /**
   * Where the other regions are, from the server rather than from the bundle.
   *
   * The client asks its OWN origin this and then pings whatever it names, which is what lets a
   * region be added or moved by editing one environment variable — no rebuild, and no bundle
   * shipping a hostname that stopped existing. `self` is how the menu avoids drawing the
   * server you are already talking to twice, once under its region name and once as "here".
   */
  if (req.url === '/regions') {
    res.writeHead(200, {
      ...CORS,
      'content-type': 'application/json; charset=utf-8',
      // Short, not none: it changes when a deploy changes, which is rarely, but a menu that
      // reopens ten times in a minute should not ask ten times.
      'cache-control': 'public, max-age=60',
    });
    res.end(JSON.stringify({ self: REGION, regions: PEERS }));
    return;
  }

  const abs = resolveFile(req.url ?? '/');
  if (!abs) {
    res.writeHead(403).end('forbidden');
    return;
  }

  try {
    const body = await readFile(abs);
    res.writeHead(200, {
      'content-type': MIME[extname(abs).toLowerCase()] ?? 'application/octet-stream',
      // The bundle's name carries its own hash, so it can be cached hard; index.html names
      // it and must not be, or a deploy would keep handing out the previous build.
      'cache-control': abs.endsWith('index.html') ? 'no-cache' : 'public, max-age=31536000, immutable',
    });
    res.end(body);
  } catch {
    // Nothing there. In a dev run that is every page request — vite is serving the client on
    // its own port and this process is only here for the socket — so the message says which
    // of the two situations it is rather than a bare 404.
    res.writeHead(404, { 'content-type': 'text/plain; charset=utf-8' });
    res.end('no client build here — run `npm run build`, or use `npm run dev` and load vite');
  }
}

const server = createServer((req, res) => {
  serveStatic(req, res).catch(() => {
    if (!res.headersSent) res.writeHead(500);
    res.end();
  });
});

// Attached to the http server rather than given a port of its own: `ws` then only claims
// requests carrying the upgrade header and leaves the rest to the handler above.
const wss = new WebSocketServer({ server });

/** One tiny application-level request per second is enough for a readable scoreboard. */
const PING_MS = 1000;
/** A lost request may not stop measurement for the rest of the match. */
const PING_STALE_MS = 5000;

wss.on('connection', (ws) => {
  // An unpredictable token can only be echoed after this player's JavaScript receives it.
  // That keeps both ends of the duration on this process without trusting a client-supplied
  // number, and unlike ws.ping() the round trip cannot stop at Render's proxy edge.
  let rtt = 0;
  let sentAt = 0;
  let nonce = '';
  const beat = setInterval(() => {
    if (ws.readyState !== ws.OPEN) return;
    const now = performance.now();
    if (sentAt && now - sentAt < PING_STALE_MS) return;
    nonce = randomUUID();
    sentAt = now;
    try {
      ws.send(encode({ t: MSG.PING, n: nonce }));
    } catch {
      sentAt = 0;
      nonce = '';
    }
  }, PING_MS);

  // The three calls the host needs from a transport. `readyState` is compared against the
  // socket's own OPEN rather than the class constant, which is what ws documents.
  const conn = host.connect({
    send: (payload) => ws.send(payload),
    isOpen: () => ws.readyState === ws.OPEN,
    rtt: () => rtt,
  });

  const gone = () => {
    clearInterval(beat);
    conn.drop();
  };

  ws.on('message', (raw) => {
    const m = decode(raw);
    if (m?.t === MSG.PONG) {
      if (!sentAt || m.n !== nonce) return;
      const sample = performance.now() - sentAt;
      sentAt = 0;
      nonce = '';
      rtt = rtt ? rtt * 0.8 + sample * 0.2 : sample;
      return;
    }
    conn.message(raw);
  });
  ws.on('close', gone);
  ws.on('error', gone);
});

server.listen(PORT, () => {
  console.log(
    `fpsbone server on port ${PORT}  (${C.TICK_HZ}Hz sim, ${C.SNAPSHOT_HZ}Hz snapshots)`,
  );
  console.log(`  game    ws://localhost:${PORT}`);
  console.log(`  client  http://localhost:${PORT}/  (from dist/, if built)`);
  console.log(
    `  modes live: ${host.available.join(', ')}`
    + `${host.pending.length ? `  |  pending: ${host.pending.join(', ')}` : ''}`,
  );
  // Said out loud because getting it wrong is invisible from here and obvious to players: a
  // server whose FPSBONE_REGION is unset still works, still holds matches, and shows up in
  // nobody's region list as anything but "this server".
  console.log(
    `  region  ${REGION ? `${REGION} (${REGIONS[REGION].label} — ${REGIONS[REGION].where})` : 'unset — this process is just "here"'}`,
  );
  console.log(
    `  peers   ${PEERS.length ? PEERS.map((r) => `${r.id} ${r.host}`).join('  ') : 'none — FPSBONE_REGIONS is unset, so the menu offers this server alone'}`,
  );
  if (BAD_PEERS.length) {
    console.log(`  IGNORED in FPSBONE_REGIONS: ${BAD_PEERS.join(' ')}  (unknown id, bad url, or a duplicate)`);
  }
});

/** The host decides the interval; this only obeys it. `advance()` returns the wait because
 *  the accumulator inside it is the thing that knows how much of a step is already banked. */
function loop() {
  setTimeout(loop, host.advance());
}
loop();
